name: Build Documentation Site

on:
  workflow_dispatch:
  schedule:
  - cron: '0 2 * * *'
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - uses: actions/checkout@v2
        with:
          ref: dev
          path: dev
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name : Install dependencies
        run: |
          wget https://github.com/dotnet/docfx/releases/download/v2.51/docfx.zip
          sudo unzip docfx.zip -d /usr/local/lib/docfx
          rm docfx.zip
          echo '#!/bin/sh' | sudo tee -a /usr/local/bin/docfx > /dev/null
          echo 'exec `which mono` $MONO_OPTIONS /usr/local/lib/docfx/docfx.exe "$@"' | sudo tee -a /usr/local/bin/docfx > /dev/null
          sudo chmod +x /usr/local/bin/docfx
      - name: Build docs
        shell: pwsh
        run: |
          ./dev/pages/Build-Site.ps1
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.2.1
        with:
          cwd: ./gh-pages
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: ./gh-pages
