name: Build External Help

on:
  workflow_dispatch:
  push:
    branches: [ dev ]
    paths: 'documentation/**'
  pull_request:
    branches: [ dev ]
    paths: 'documentation/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev
    - name: Build and Publish Module
      env:
        POWERSHELLGALLERY_API_KEY: ${{ secrets.POWERSHELLGALLERY_API_KEY }}
      shell: pwsh
      run: |
        ./build/Build-HelpFile.ps1
