name: PRCheck

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PnP.Framework
      uses: actions/checkout@v2
      with:
        repository: pnp/pnpframework
        path: pnpframework
        ref: 'dev'
    - name: Checkout PnP.PowerShell
      uses: actions/checkout@v2
      with:
        path: powershell
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0
    - name: Install PnP.Framework dependencies
      run: dotnet restore
      working-directory: pnpframework/src/lib
    - name: Build PnP.Framework
      run: dotnet build --configuration Release --no-restore
      working-directory: pnpframework/src/lib
    - name: Install PnP.PowerShell dependencies
      run: dotnet restore
      working-directory: powershell/src
    - name: Build PnP.PowerShell
      run: dotnet build --configuration Release --no-restore -p:LocalPnPFramework=true
